 export const movies = {
  "results": [
    
    {
      "adult": false,
      "backdrop_path": null,
      "genre_ids": [18],
      "id": 814820,
      "original_language": "en",
      "original_title": "All for Her",
      "overview": "When a woman finally becomes pregnant but is diagnosed with a deadly condition, she must lean on her family to save her unborn child.",
      "popularity": 76.436,
      "poster_path": "/Qef2eyZhTFGE7Ul9RhKvMuPnYM.jpg",
      "release_date": "2021-09-13",
      "title": "All for Her",
      "video": false,
      "vote_average": 4,
      "vote_count": 2
    },
    {
      "adult": false,
      "backdrop_path": "/gPKcJzrbgs1670fOeKN1xQH9mNa.jpg",
      "genre_ids": [80, 18, 9648, 53],
      "id": 823855,
      "original_language": "en",
      "original_title": "I Am All Girls",
      "overview": "A special crimes investigator forms an unlikely bond with a serial killer to bring down a global child sex trafficking syndicate.",
      "popularity": 86.127,
      "poster_path": "/m6bUeV4mczG3z2YXXr5XDKPsQzv.jpg",
      "release_date": "2021-05-14",
      "title": "I Am All Girls",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 162
    },
    {
      "adult": false,
      "backdrop_path": "/oSY7vsYlScliVKomRNviGuWXykC.jpg",
      "genre_ids": [35, 10749],
      "id": 10314,
      "original_language": "en",
      "original_title": "She's All That",
      "overview": "High school hotshot Zach Siler is the envy of his peers. But his popularity declines sharply when his cheerleader girlfriend, Taylor, leaves him for sleazy reality-television star Brock Hudson. Desperate to revive his fading reputation, Siler agrees to a seemingly impossible challenge. He has six weeks to gain the trust of nerdy outcast Laney Boggs -- and help her to become the school's next prom queen.",
      "popularity": 39.379,
      "poster_path": "/a0pepZNFCjggc7Na9gEwbTI1f46.jpg",
      "release_date": "1999-01-29",
      "title": "She's All That",
      "video": false,
      "vote_average": 6.3,
      "vote_count": 1548
    },
    {
      "adult": false,
      "backdrop_path": "/cb1R4VdM0FkacQ8AYjuK9Qe6Lpl.jpg",
      "genre_ids": [28, 18, 53, 80],
      "id": 241554,
      "original_language": "en",
      "original_title": "Run All Night",
      "overview": "Brooklyn mobster and prolific hit man Jimmy Conlon has seen better days. Longtime best friend of a mob boss, Jimmy is haunted by the sins of his past—as well as a dogged police detective who’s been one step behind Jimmy for 30 years. But when Jimmy’s estranged son becomes a target, Jimmy must make a choice between the crime family he chose and the real family he abandoned long ago. Now, with nowhere safe to turn, Jimmy has just one night to figure out exactly where his loyalties lie and to see if he can finally make things right.",
      "popularity": 33.032,
      "poster_path": "/frzdzHceByAIlwVKvSvY9zqpjyV.jpg",
      "release_date": "2015-03-11",
      "title": "Run All Night",
      "video": false,
      "vote_average": 6.4,
      "vote_count": 2283
    },
    {
      "adult": false,
      "backdrop_path": "/7Gzsn4yiwMSXvYcbWXsoDhq8QO2.jpg",
      "genre_ids": [10749, 18],
      "id": 632322,
      "original_language": "en",
      "original_title": "All My Life",
      "overview": "It was a chance meeting started by one of Sol’s friends trying to chat up Jennifer. However, in the end, it was those two who hit it off. Sol enjoyed Jen’s smile, her effort, and how silly she could be. Jen enjoyed Sol’s cooking, his athleticism, and that he would join her in fun moments. As you can imagine, love bloomed, and things got serious. Jen’s investment in Sol led to her pushing him to follow his dreams and even move in to save money. Sol’s investment in Jen well, it led to him proposing. But what started as a liver tumor grew into full-on cancer, so with a diagnosis of 6 months to live, Sol and Jennifer try to make the best of it.",
      "popularity": 29.524,
      "poster_path": "/xoKZ4ZkVApcTaTYlGoZ3J8xcIzG.jpg",
      "release_date": "2020-10-23",
      "title": "All My Life",
      "video": false,
      "vote_average": 8.1,
      "vote_count": 280
    },
    {
      "adult": false,
      "backdrop_path": "/zxoPzzBGimgXha8YjvmahUedz4j.jpg",
      "genre_ids": [18, 35],
      "id": 450806,
      "original_language": "en",
      "original_title": "All Saints",
      "overview": "ALL SAINTS is based on the inspiring true story of salesman-turned-pastor Michael Spurlock, the tiny church he was ordered to shut down, and a group of refugees from Southeast Asia. Together, they risked everything to plant seeds for a future that might just save them all.",
      "popularity": 20.432,
      "poster_path": "/sIE5BafMU0gPYOqBSiYzTxmHqGM.jpg",
      "release_date": "2017-08-25",
      "title": "All Saints",
      "video": false,
      "vote_average": 6.2,
      "vote_count": 44
    },
    {
      "adult": false,
      "backdrop_path": "/in3BOlhrd3wNOuzIxToU3WGw9AO.jpg",
      "genre_ids": [28, 80],
      "id": 449503,
      "original_language": "en",
      "original_title": "Kill 'em All",
      "overview": "After a massive shootout, a mysterious stranger arrives at a local hospital on the brink of death. Then, a foreign gang brazenly comes to the hospital to hunt him down. His nurse, the sole surviving witness to the follow-up shootout, must face an FBI interrogation that unlocks a plot of international intrigue and revenge.",
      "popularity": 19.872,
      "poster_path": "/cWkZQqS2IxMcvH7UZSHFR8YYRfk.jpg",
      "release_date": "2017-06-06",
      "title": "Kill 'em All",
      "video": false,
      "vote_average": 5.5,
      "vote_count": 67
    },
    {
      "adult": false,
      "backdrop_path": "/tcrNJfyNEIqaBR8Ogkgnq5xQJnf.jpg",
      "genre_ids": [10749, 18],
      "id": 342470,
      "original_language": "en",
      "original_title": "All the Bright Places",
      "overview": "Two teens facing personal struggles form a powerful bond as they embark on a cathartic journey chronicling the wonders of Indiana.",
      "popularity": 40.366,
      "poster_path": "/4SafxuMKQiw4reBiWKVZJpJn80I.jpg",
      "release_date": "2020-02-28",
      "title": "All the Bright Places",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 2185
    },
    {
      "adult": false,
      "backdrop_path": "/qjhcTGnjxYJqwBGlDzZkYWmne6e.jpg",
      "genre_ids": [10749, 35, 18],
      "id": 614409,
      "original_language": "en",
      "original_title": "To All the Boys: Always and Forever",
      "overview": "Senior year of high school takes center stage as Lara Jean returns from a family trip to Korea and considers her college plans — with and without Peter.",
      "popularity": 51.863,
      "poster_path": "/iepqdM52f4w75fNcvgRF5QoIAjm.jpg",
      "release_date": "2021-02-12",
      "title": "To All the Boys: Always and Forever",
      "video": false,
      "vote_average": 7.8,
      "vote_count": 1406
    },
    {
      "adult": false,
      "backdrop_path": "/1642Z6Jz4YtrFa5YJyN6N6FrD8M.jpg",
      "genre_ids": [10402, 18],
      "id": 402529,
      "original_language": "en",
      "original_title": "All Eyez on Me",
      "overview": "All Eyez on Me chronicles the life and legacy of Tupac Shakur, including his rise to superstardom as a hip-hop artist, actor, poet and activist, as well as his imprisonment and prolific, controversial time at Death Row Records. Against insurmountable odds, Tupac rose to become a cultural icon whose career and persona both continue to grow long after his passing.",
      "popularity": 26.238,
      "poster_path": "/zmgsaKFWbmZ1Grz4SO0PLNxilv3.jpg",
      "release_date": "2017-06-12",
      "title": "All Eyez on Me",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 976
    },
    {
      "adult": false,
      "backdrop_path": "/cFgHrvRjoRHOrtolzrJov7v4s54.jpg",
      "genre_ids": [10749, 18, 10402],
      "id": 243683,
      "original_language": "en",
      "original_title": "Step Up All In",
      "overview": "All-stars from the previous Step Up installments come together in glittering Las Vegas, battling for a victory that could define their dreams and their careers.",
      "popularity": 20.731,
      "poster_path": "/bM9U2WDQKeQhdQX4kwdk72Drpaz.jpg",
      "release_date": "2014-07-16",
      "title": "Step Up All In",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 1669
    },
    {
      "adult": false,
      "backdrop_path": "/xXhta1NIKn09IXy0mfp68cabdWS.jpg",
      "genre_ids": [35, 10749],
      "id": 466282,
      "original_language": "en",
      "original_title": "To All the Boys I've Loved Before",
      "overview": "Lara Jean's love life goes from imaginary to out of control when her secret letters to every boy she's ever fallen for are mysteriously mailed out.",
      "popularity": 47.184,
      "poster_path": "/hKHZhUbIyUAjcSrqJThFGYIR6kI.jpg",
      "release_date": "2018-08-16",
      "title": "To All the Boys I've Loved Before",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 7304
    },
    {
      "adult": false,
      "backdrop_path": "/vT2rEtt3kK2Vo6v5yXYd2y3dk14.jpg",
      "genre_ids": [28],
      "id": 481203,
      "original_language": "en",
      "original_title": "All the Devil's Men",
      "overview": "A battle-scarred War on Terror bounty hunter is forced to go to London on a manhunt for a disavowed CIA operative, which leads him into a deadly running battle with a former military comrade and his private army.",
      "popularity": 14.873,
      "poster_path": "/pnlwh6CBBq5jB7G7OVxDsfz1b9v.jpg",
      "release_date": "2018-05-12",
      "title": "All the Devil's Men",
      "video": false,
      "vote_average": 6,
      "vote_count": 102
    },
    {
      "adult": false,
      "backdrop_path": "/66viVL7ML2Vr8IHVJrVw8OjEmMW.jpg",
      "genre_ids": [16, 878, 10751, 28],
      "id": 96826,
      "original_language": "en",
      "original_title": "Ben 10: Destroy All Aliens",
      "overview": "Based on the original animated series Ben 10.  Ben becomes targeted by an evil Mechamorph Warrior, named \"Retaliator,\" who mistakenly blames Ben for something he did not do and attempts to destroy all aliens.",
      "popularity": 26.295,
      "poster_path": "/qoILNllyC6YXHyT4V9YOhMJlPuO.jpg",
      "release_date": "2012-03-11",
      "title": "Ben 10: Destroy All Aliens",
      "video": false,
      "vote_average": 6.1,
      "vote_count": 37
    },
    {
      "adult": false,
      "backdrop_path": "/ooBIm7ZBa1Xo4d1dv4AY73HKctF.jpg",
      "genre_ids": [27],
      "id": 231001,
      "original_language": "en",
      "original_title": "All Hallows' Eve",
      "overview": "While watching two children on Halloween night, a babysitter finds an old VHS tape in the kids' trick or treat bag. The tape features three tales of terror, all linked together by a murderous clown.",
      "popularity": 9.472,
      "poster_path": "/bSe8CBqK8HkbP6sqZWzcJfQV9Ci.jpg",
      "release_date": "2013-10-29",
      "title": "All Hallows' Eve",
      "video": false,
      "vote_average": 5.9,
      "vote_count": 183
    },
    {
      "adult": false,
      "backdrop_path": "/j7Sg03Zcfs03vVdEtAiZoceNNOe.jpg",
      "genre_ids": [878, 16, 28, 12],
      "id": 56590,
      "original_language": "en",
      "original_title": "All Star Superman",
      "overview": "Lex Luthor enacts his plan to rid the world of Superman, once and for all. Succeeding with solar radiation poisoning, the Man of Steel is slowly dying. With what little times remains, the Last Son of Krypton must confront the revealing of his secret identity to Lois Lane and face Luthor in a final battle.",
      "popularity": 12.647,
      "poster_path": "/xoBULL2YZUSDhqTkIvX0EvIl9Fj.jpg",
      "release_date": "2011-02-22",
      "title": "All Star Superman",
      "video": false,
      "vote_average": 6.9,
      "vote_count": 335
    },
    {
      "adult": false,
      "backdrop_path": "/qvLjTAwwQTcAiYXxnGaXctlqUJ6.jpg",
      "genre_ids": [18, 36, 9648, 53],
      "id": 891,
      "original_language": "en",
      "original_title": "All the President's Men",
      "overview": "During the 1972 elections, two reporters' investigation sheds light on the controversial Watergate scandal that compels President Richard Nixon to resign from his post.",
      "popularity": 14.394,
      "poster_path": "/cPtSHR7D2WGsDBfnC5DxV927hKn.jpg",
      "release_date": "1976-04-04",
      "title": "All the President's Men",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 1282
    },
    {
      "adult": false,
      "backdrop_path": "/ah1WWJWFS17uKVKhKr0nKSSVgiH.jpg",
      "genre_ids": [35],
      "id": 510452,
      "original_language": "fr",
      "original_title": "All Inclusive",
      "overview": "Planted by his fiancee at the airport, Bruno flies away alone for a week in an All Inclusive Caribbean vacation club. Bad news never comes alone, he will have to share his room with Jean-Paul Cisse, eternal bachelor very invading .",
      "popularity": 8.855,
      "poster_path": "/sKcPccGVDmst7TC0MYEgsP3fj6p.jpg",
      "release_date": "2019-02-13",
      "title": "All Inclusive",
      "video": false,
      "vote_average": 4,
      "vote_count": 246
    },
    {
      "adult": false,
      "backdrop_path": "/rcGg4bZ1SH9ZDuhyWrXNivQaoLk.jpg",
      "genre_ids": [35],
      "id": 352501,
      "original_language": "en",
      "original_title": "All Nighter",
      "overview": "When a globe-trotting, workaholic father trying to visit his daughter on a last minute layover in Los Angeles discovers that she’s disappeared, he forces her awkward, nervous ex-boyfriend, still nursing a broken heart, to help him find her over the course of one increasingly crazy night.",
      "popularity": 9.805,
      "poster_path": "/ciNUrbNv871umQ3IqvIOjet4s4E.jpg",
      "release_date": "2017-03-10",
      "title": "All Nighter",
      "video": false,
      "vote_average": 5.8,
      "vote_count": 166
    }
  ],
  "total_pages": 347,
  "total_results": 6938
}


